export const items = [
  {
    id: 1,
    unitCode: 10081,
    unitCompany: '어디야',
    unitName: '고구마',
    useId: 'reasm04',
    groupName: 'apple',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
  {
    id: 2,
    unitCode: 10081,
    unitCompany: '어디야',
    unitName: '감자',
    useId: 'reasm04',
    groupName: 'apple',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
  {
    id: 3,
    unitCode: 10081,
    unitCompany: '어디야',
    unitName: '당근',
    useId: 'reasm04',
    groupName: 'abc',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
  {
    id: 4,
    unitCode: 10081,
    unitCompany: '어디야',
    unitName: '어디야',
    useId: 'reasm04',
    groupName: 'abc',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
  {
    id: 5,
    unitCode: 10081,
    unitCompany: '이디야',
    unitName: '어디야',
    useId: 'reasm04',
    groupName: 'abc',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
  {
    id: 6,
    unitCode: 10081,
    unitCompany: '어디야',
    unitName: '고구마',
    useId: 'reasm04',
    groupName: 'apple',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
  {
    id: 7,
    unitCode: 10081,
    unitCompany: '어디야',
    unitName: '감자',
    useId: 'reasm04',
    groupName: 'apple',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
  {
    id: 8,
    unitCode: 10081,
    unitCompany: '어디야',
    unitName: '당근',
    useId: 'reasm04',
    groupName: 'abc',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
  {
    id: 9,
    unitCode: 10081,
    unitCompany: '어디야',
    unitName: '어디야',
    useId: 'reasm04',
    groupName: 'abc',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
  {
    id: 10,
    unitCode: 10081,
    unitCompany: '이디야',
    unitName: '어디야',
    useId: 'reasm04',
    groupName: 'abc',
    sponsorCode: true,
    autoCheck: true,
    autoInvoice: true,
    partialDelivery: true,
    autoCancelB: true,
    autoCancelA: true,
    cancelAble: true,
    agreeCancel: true,
    csLink: true,
    noticeBoard: true,
  },
];
